### ISSUE TITLE
Avoiding installation of *what libraries when installing SCT extensions

### ISSUE THREAD

**Issue by rv2e** [datacamp/protowhat#18]
@machow commented on [Wed Jan 03 2018](https://github.com/datacamp/learn-bugs/issues/136)

## Summary of the issue

There are two images for a course

* course image: contains course specific libraries
* shared image: contains backends, SCT libs, etc...

When building a course image, even though SCT extensions depend on SCT libraries, they don't need to install them (since they're already on the shared_image). However, because the shared_image isn't mounted when building a course, tools like `pip` can't know this, and will install them by default. 

This issue also arose in the shell course.

**solutions**

1. use the --no-deps flag, e.g. `pip install --no-deps sqlwhat-ext`
2. remove the relevant SCT library as a dependency in the , e.g. sqlwhat-ext package

(1) seems to make more sense from a package development point of view, but (2) probably is less risky, more annoying to develop with.

**Comment by machow** [comment]
Just a note, I noticed that one of the course templates included the correct line for pip installing an extension in the `requirements.sh`, which seems like a great way to handle this :)

**Comment by filipsch** [comment]
See https://github.com/datacamp/content-engineering-features/issues/6 for more context. Extension packages were only used in production in Shell and SQL

**SQL**
https://github.com/datacamp/courses-msft-transact-sql-final-lab -> OK (uses --no-deps)
https://github.com/datacamp/courses-msft-transact-sql -> OK (uses --no-deps)
https://github.com/datacamp/courses-joining-data-in-postgresql -> OK (uses --no-deps)

**Shell**
https://github.com/datacamp/courses-conda-essentials -> OK (uses --no-deps)
https://github.com/datacamp/courses-intro-to-unix-shell/ -> NOK (needs --no-deps)
https://github.com/datacamp/courses-intro-to-git/ -> NOK (needs --no-deps)

The latter two here will be fixed when Git and Shell are investigated.

**Comment by filipsch** [comment]
This is all done now.
