### ISSUE TITLE
Allow chaining from test_or

### ISSUE THREAD

**Issue by gvwilson** [datacamp/protowhat#23]
As an SCT author, I want to be able to write:

```
Ex() >> test_or(test_1(...), test_2(...)) >> test_3(...)
```

However, `test_or` doesn't return the `state` object, so attempts to chain from it in this way result in complaints about `NoneType` not having certain methods. It's possible to get around this in some cases by reversing the order of the tests (i.e., running `test_3` before `test_or`), but sometimes `test_3` only makes sense if one or the other preconditions passed.

**Comment by filipsch** [comment]
Thanks for the suggestion. However, I think it is not very clear about what is happening. I favor readability over DRY for these edge cases. Closing until somebody else thinks the same about it.
