### ISSUE TITLE
Create mock library for documentation purposes

### ISSUE THREAD

**Issue by filipsch** [datacamp/protowhat#7]
It becomes a bit hard to understand :)

**Comment by machow** [comment]
This is now done in the following notebooks

https://github.com/datacamp/protowhat/blob/master/example/example_basic.ipynb

https://github.com/datacamp/protowhat/blob/master/example/example_python.ipynb

@filipsch you may be interested in the second, which shows how to add a python parser to protowhat, including pulling out the text being focused on (using the `asttokens` package) ;)

**Comment by filipsch** [comment]
@machow very nice!
